version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=54321
      - POSTGRES_DB=postgres
    volumes:
      - ./base:/var/lib/postgresql/data
    restart: always